---
- name: reboot | Pre-reboot check if we can reach polling port
  wait_for: host={{ ip_to_probe }} port={{ port_to_probe }} delay=0 timeout={{ pre_reboot_timeout }}
  when: not skip_pre_reboot_check

- name: reboot | Reboot server if required
  shell: "nohup bash -c 'sleep {{ reboot_delay }}; reboot' &"
  args:
   removes: '{{ omit if force_reboot else reboot_flag }}'
  register: reboot
  become: true

- name: reboot | Wait until boot is complete
  wait_for: host={{ ip_to_probe }} port={{ port_to_probe }} delay={{ delay_before_probe }} timeout={{ probe_timeout }}
  connection: local
  when: reboot is changed or force_reboot
  changed_when: true
